spring.application.name=WeatherApplication
weather.api.key= QXAE98FVU5MWGEA5VSCUTYGVA
weather.api.base-url= https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/
#Redis container is running in local
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.redis.time-to-live=60000
spring.cache.type=redis
#spring.cache.redis.ignore-exceptions=true
#spring.cache.redis.enable-statistics=true
